### ISSUE TITLE
Crash opening world

### ISSUE THREAD

**Issue by KaiiserAmil** [derfl007/df-roads#22] opened 2018-12-13 21:59 UTC
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Version this happens in**
Minecraft:
Mod:

**Additional context**

---- Minecraft Crash Report ----

WARNING: coremods are present:
  MalisisSwitchesPlugin (malisisswitches-1.12.2-5.1.0.jar)
  MalisisCorePlugin (malisiscore-1.12.2-6.4.0.jar)
  CreativePatchingLoader (CreativeCore_v1.9.35_mc1.11.2.jar)
  EDFMLLoadingPlugin (stairdoors-1.5.jar)
  EnderCorePlugin (EnderCore-1.12.2-0.5.43.jar)
  ObfuscatePlugin (obfuscate-0.2.6-1.12.2.jar)
  AdvancedRocketryPlugin (AdvancedRocketry-1.12.2-1.4.1-113-universal.jar)
  MovingWorldCore (movingworld-1.12-6.342-full.jar)
  NWRTweak (redstonepaste-mc1.12-1.7.5.jar)
Contact their authors BEFORE contacting forge

// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 12/13/18 9:16 PM
Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
	at derfl007.roads.common.tileentities.TileEntityRoadLantern.func_73660_a(TileEntityRoadLantern.java:25)
	at net.minecraft.world.World.func_72939_s(World.java:1835)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at derfl007.roads.common.tileentities.TileEntityRoadLantern.func_73660_a(TileEntityRoadLantern.java:25)

-- Block entity being ticked --
Details:
	Name: df-roads:road_lantern // derfl007.roads.common.tileentities.TileEntityRoadLantern
	Block type: ID #1233 (tile.road_lantern_lit // derfl007.roads.common.blocks.BlockRoadLantern // df-roads:road_lantern_lit)
	Block data value: 3 / 0x3 / 0b0011
	Block location: World: (185,28,-1068), Chunk: (at 9,1,4 in 11,-67; contains blocks 176,0,-1072 to 191,255,-1057), Region: (0,-3; contains chunks 0,-96 to 31,-65, blocks 0,0,-1536 to 511,255,-1025)
	Actual block type: ID #1233 (tile.road_lantern_lit // derfl007.roads.common.blocks.BlockRoadLantern // df-roads:road_lantern_lit)
	Actual block data value: 3 / 0x3 / 0b0011
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1835)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)

-- Affected level --
Details:
	Level name: Kaisey World
	All players: 1 total; [EntityPlayerMP['Kaisey'/117, l='Kaisey World', x=161.16, y=25.00, z=-1038.83]]
	Chunk stats: ServerChunkCache: 626 Drop: 0
	Level seed: 322400980689971542
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 3;minecraft:bedrock,20*minecraft:stone,3*minecraft:dirt,minecraft:grass;1;village
	Level spawn location: World: (151,4,-1031), Chunk: (at 7,0,9 in 9,-65; contains blocks 144,0,-1040 to 159,255,-1025), Region: (0,-3; contains chunks 0,-96 to 31,-65, blocks 0,0,-1536 to 511,255,-1025)
	Level time: 4207720 game time, 1822304 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 931 (now: false), thunder time: 94420 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_191, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1298105368 bytes (1237 MB) / 3299827712 bytes (3146 MB) up to 8446541824 bytes (8055 MB)
	JVM Flags: 3 total; -Xmn128M -Xmx8067M -XX:+UseConcMarkSweepGC
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2768 Optifine OptiFine_1.12.2_HD_U_E2 54 mods loaded, 54 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State     | ID                                           | Version       | Source                                                | Signature                                |
	|:--------- |:-------------------------------------------- |:------------- |:----------------------------------------------------- |:---------------------------------------- |
	| UCHIJAAAA | minecraft                                    | 1.12.2        | minecraft.jar                                         | None                                     |
	| UCHIJAAAA | mcp                                          | 9.42          | minecraft.jar                                         | None                                     |
	| UCHIJAAAA | FML                                          | 8.0.99.99     | forge-1.12.2-14.23.5.2768.jar                         | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | forge                                        | 14.23.5.2768  | forge-1.12.2-14.23.5.2768.jar                         | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | advancedrocketrycore                         | 1             | minecraft.jar                                         | None                                     |
	| UCHIJAAAA | creativecoredummy                            | 1.0.0         | minecraft.jar                                         | None                                     |
	| UCHIJAAAA | com.elytradev.movingworld.common.asm.coremod |               | minecraft.jar                                         | None                                     |
	| UCHIJAAAA | obfuscate                                    | 0.2.6         | minecraft.jar                                         | None                                     |
	| UCHIJAAAA | securitycraft                                | v1.8.10       | [1.12.2]+SecurityCraft+v1.8.10.jar                    | None                                     |
	| UCHIJAAAA | libvulpes                                    | 0.3.0.-44     | LibVulpes-1.12.2-0.3.0-44-universal.jar               | None                                     |
	| UCHIJAAAA | advancedrocketry                             | 1.4.1.-113    | AdvancedRocketry-1.12.2-1.4.1-113-universal.jar       | None                                     |
	| UCHIJAAAA | architecturecraft                            | @VERSION@     | ArchitectureCraft-1.12-3.80.jar                       | None                                     |
	| UCHIJAAAA | cdm                                          | 0.4.1         | cdm-0.4.1-mc1.12.2.jar                                | None                                     |
	| UCHIJAAAA | cfm                                          | 6.0.0         | cfm-6.0.0-mc1.12.2.jar                                | None                                     |
	| UCHIJAAAA | cgm                                          | 0.9.2         | cgm-0.9.2-mc1.12.2.jar                                | None                                     |
	| UCHIJAAAA | cjcm                                         | 1.0           | cjcm-1.0.jar                                          | None                                     |
	| UCHIJAAAA | codechickenlib                               | 3.2.2.353     | CodeChickenLib-1.12.2-3.2.2.353-universal.jar         | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJAAAA | creativecore                                 | 1.9.9         | CreativeCore_v1.9.35_mc1.11.2.jar                     | None                                     |
	| UCHIJAAAA | movingworld                                  | 1.12-6.342    | movingworld-1.12-6.342-full.jar                       | None                                     |
	| UCHIJAAAA | davincisvessels                              | @DVESSELSVER@ | davincisvessels-1.12-6.340-full.jar                   | None                                     |
	| UCHIJAAAA | df-roads                                     | 1.5-mc1.12.2  | df-roads-1.5-mc1.12.2.jar                             | None                                     |
	| UCHIJAAAA | endercore                                    | 1.12.2-0.5.43 | EnderCore-1.12.2-0.5.43.jar                           | None                                     |
	| UCHIJAAAA | jei                                          | 4.13.1.225    | jei_1.12.2-4.13.1.225.jar                             | None                                     |
	| UCHIJAAAA | enderio                                      | 5.0.38        | EnderIO-base-1.12.2-5.0.38.jar                        | None                                     |
	| UCHIJAAAA | enderiointegrationtic                        | 5.0.38        | EnderIO-integration-tic-1.12.2-5.0.38.jar             | None                                     |
	| UCHIJAAAA | enderiobase                                  | 5.0.38        | EnderIO-base-1.12.2-5.0.38.jar                        | None                                     |
	| UCHIJAAAA | enderioconduits                              | 5.0.38        | EnderIO-conduits-1.12.2-5.0.38.jar                    | None                                     |
	| UCHIJAAAA | enderiopowertools                            | 5.0.38        | EnderIO-conduits-1.12.2-5.0.38.jar                    | None                                     |
	| UCHIJAAAA | enderioconduitsappliedenergistics            | 5.0.38        | EnderIO-conduits-appliedenergistics-1.12.2-5.0.38.jar | None                                     |
	| UCHIJAAAA | enderioconduitsopencomputers                 | 5.0.38        | EnderIO-conduits-opencomputers-1.12.2-5.0.38.jar      | None                                     |
	| UCHIJAAAA | enderioconduitsrefinedstorage                | 5.0.38        | EnderIO-conduits-refinedstorage-1.12.2-5.0.38.jar     | None                                     |
	| UCHIJAAAA | enderiointegrationforestry                   | 5.0.38        | EnderIO-integration-forestry-1.12.2-5.0.38.jar        | None                                     |
	| UCHIJAAAA | enderiointegrationticlate                    | 5.0.38        | EnderIO-integration-tic-1.12.2-5.0.38.jar             | None                                     |
	| UCHIJAAAA | gitwebbuilder                                | 1.1           | GitWeb+Builder-1.1.jar                                | None                                     |
	| UCHIJAAAA | waila                                        | 1.8.26        | Hwyla-1.8.26-B41_1.12.2.jar                           | None                                     |
	| UCHIJAAAA | lightswitch                                  | 1.1.2         | lightswitch-1.1.2-mc1.12.2.jar                        | None                                     |
	| UCHIJAAAA | malisiscore                                  | 1.12.2-6.4.0  | malisiscore-1.12.2-6.4.0.jar                          | None                                     |
	| UCHIJAAAA | malisisdoors                                 | 1.12.2-7.3.0  | malisisdoors-1.12.2-7.3.0.jar                         | None                                     |
	| UCHIJAAAA | malisisswitches                              | 1.12.2-5.1.0  | malisisswitches-1.12.2-5.1.0.jar                      | None                                     |
	| UCHIJAAAA | radixcore                                    | 1.12.x-2.2.1  | RadixCore-1.12.x-2.2.1-universal.jar                  | None                                     |
	| UCHIJAAAA | mca                                          | 1.12.2-5.3.1  | MCA-1.12.x-5.3.1-universal.jar                        | None                                     |
	| UCHIJAAAA | mcjtylib_ng                                  | 3.0.7         | mcjtylib-1.12-3.0.7.jar                               | None                                     |
	| UCHIJAAAA | modroadworksreborn                           | 0.0.1         | modroadworksreborn-0.0.1.jar                          | None                                     |
	| UCHIJAAAA | nei                                          | 2.4.2         | NotEnoughItems-1.12.2-2.4.2.240-universal.jar         | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJAAAA | placeableitems                               | 3.3           | placeableitems-3.3.jar                                | None                                     |
	| UCHIJAAAA | realdrops                                    | 1.2.13        | Realistic-Item-Drops-Mod-1.12.2.jar                   | None                                     |
	| UCHIJAAAA | redstonepaste                                | 1.7.5         | redstonepaste-mc1.12-1.7.5.jar                        | None                                     |
	| UCHIJAAAA | rftools                                      | 7.59          | rftools-1.12-7.59.jar                                 | None                                     |
	| UCHIJAAAA | thutcore                                     | 5.19.9        | thutcore-1.12.2-5.19.9.jar                            | None                                     |
	| UCHIJAAAA | thutcore_compat                              | 1.0           | thutcore-1.12.2-5.19.9.jar                            | None                                     |
	| UCHIJAAAA | thuttech                                     | 6.1.5         | thuttech-1.12.2-6.1.5.jar                             | None                                     |
	| UCHIJAAAA | treechopper                                  | 1.2.4         | Tree-Chopper-Mod-1.12.2.jar                           | None                                     |
	| UCHIJAAAA | vehicle                                      | 0.32.0        | vehicle-0.32.0-mc1.12.2.jar                           | None                                     |
	| UCHIJAAAA | xaerominimap                                 | 1.15.9        | Xaeros_Minimap_1.15.9_Forge_1.12.jar                  | None                                     |

	Loaded coremods (and transformers): 
MalisisSwitchesPlugin (malisisswitches-1.12.2-5.1.0.jar)
  
MalisisCorePlugin (malisiscore-1.12.2-6.4.0.jar)
  
CreativePatchingLoader (CreativeCore_v1.9.35_mc1.11.2.jar)
  com.creativemd.creativecore.core.CreativeCoreTransformer
EDFMLLoadingPlugin (stairdoors-1.5.jar)
  com.darkenchanter.stairdoors.asm.EDClassTransformer
EnderCorePlugin (EnderCore-1.12.2-0.5.43.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
  com.enderio.core.common.transform.SimpleMixinPatcher
ObfuscatePlugin (obfuscate-0.2.6-1.12.2.jar)
  com.mrcrayfish.obfuscate.asm.ObfuscateTransformer
AdvancedRocketryPlugin (AdvancedRocketry-1.12.2-1.4.1-113-universal.jar)
  zmaster587.advancedRocketry.asm.ClassTransformer
MovingWorldCore (movingworld-1.12-6.342-full.jar)
  
NWRTweak (redstonepaste-mc1.12-1.7.5.jar)
  net.fybertech.nwr.NWRTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Ender IO: Found the following problem(s) with your installation (That does NOT mean that Ender IO caused the crash or was involved in it in any way. We add this information to help finding common problems, not as an invitation to post any crash you encounter to Ender IO's issue tracker. Always check the stack trace above to see which mod is most likely failing.):
                  * Optifine is installed. This is NOT supported.
                 This may (look up the meaning of 'may' in the dictionary if you're not sure what it means) have caused the error. Try reproducing the crash WITHOUT this/these mod(s) before reporting it.

	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
	!!!You are looking at the diagnostics information, not at the crash.       !!!
	!!!Scroll up until you see the line with '---- Minecraft Crash Report ----'!!!
	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['Kaisey'/117, l='Kaisey World', x=161.16, y=25.00, z=-1038.83]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	OptiFine Version: OptiFine_1.12.2_HD_U_E2
	OptiFine Build: 20180728-185429
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.0.0 - Build 10.18.10.5059
	OpenGlRenderer: Intel(R) HD Graphics
	OpenGlVendor: Intel
	CpuCount: 2

**Comment by derfl007** [comment] 2018-12-14 07:30
Duplicate of issue #19

**Closed** 2018-12-14 07:30 UTC
Labels: duplicate
